name: CI Pipeline
run-name: CI Test
on: [push]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
            - name: Checkout the code
              uses: actions/checkout@v2

            - name: Set up JDK 17
              uses: actions/setup-java@v2
              with:
                java-version: '17'
                distribution: 'adopt'

            - name: Run Lint
              run: ./gradlew lint

            - name: Upload html test report
              uses: actions/upload-artifact@v2
              with:
                name: index.html
                path: app/build/reports/lint-results-debug.html

  unit-test:
    needs: [lint]
    runs-on: ubuntu-latest
    steps:
            - name: Checkout the code
              uses: actions/checkout@v2

            - name: Set up JDK 17
              uses: actions/setup-java@v2
              with:
                java-version: '17'
                distribution: 'adopt'

            - name: Run tests
              run: ./gradlew test

            - name: Upload test report
              uses: actions/upload-artifact@v2
              with:
                name: unit_test-report
                path: app/build/reports/tests/testDebugUnitTest/
