# CI workflow to build and test an Android app.
# Sets up Java, validates Gradle, runs lint, unit tests, code coverage.
# Builds unsigned APK and uploads as artifact.
# Workflow runs on ubuntu-latest and uses matrix build for gradle version.

name: CI (unsigned APK)
run-name: Gradle CI
on:
  workflow_call: # required when creating a reusable workflow
#    inputs:
#      config-path:
#        required: false
#        type: string
#    secrets:
#      token:
#        required: false
jobs:
  build-and-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        gradle-version: [ 8.2.1 ]

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@ccb4328a959376b642e027874838f60f8e596de3
      - name: Run the Gradle package task
        uses: gradle/gradle-build-action@749f47bda3e44aa060e82d7b3ef7e40d953bd629
      #          #        with:
      #        # Can include this if we decide to add our own customized gradle package
      #      #          arguments: -b ci.gradle package
      #
      #      # dependencies automatically installed by gradle

      - name: Lint code
        run: ./gradlew lint
      - name: Compile Tests
        run: ./gradlew compileDebugAndroidTestKotlin

      - name: Run unit tests
        run: ./gradlew test

      - name: Code coverage
        run: ./gradlew koverhtmlreport

      # Build workflow and save as artifact
      # Gradle will automatically compile Kotlin when running tasks like build. This step explicitly validates Kotlin.
      # If there are Kotlin compile errors, this step will fail and you'll see the compilation issues in the logs.
      - name: Build with Gradle
        uses: gradle/gradle-build-action@749f47bda3e44aa060e82d7b3ef7e40d953bd629
        with:
          arguments: build
      - uses: actions/upload-artifact@v3
        with:
          name: Unsigned_APK
          path: app/build/outputs/apk/release/app-release-unsigned.apk
