
# Pull request workflow to run CI on PRs.
# Triggered on opened or reopened pull requests.
# Defines one job that reuses the ci.yml workflow.
# ci.yml will run lint, tests, coverage, build for the PR.


name: CI (on pull-request)
run-name: PR from branch ${{ github.ref }}
# Will run CI workflow on an opened or reopened PR for easy reference. For compilation, unit tests, code coverage etc.
on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - '**.kt'
      - '**/*.xml'  # Matches all XML files in any directory
      - '**/*.png'  # Matches all PNG files in any directory
      # Add any other file patterns you need to include

jobs:
  Continuous-Integration:
    uses: ./.github/workflows/ci.yml
